[
  "ihaskell-aeson"
  "ihaskell-blaze"
  "ihaskell-charts"
  "ihaskell-diagrams"
  "ihaskell-gnuplot"
  "ihaskell-graphviz"
  "ihaskell-hatex"
  "ihaskell-juicypixels"
  "ihaskell-magic"
  "ihaskell-plot"
  # "ihaskell-rlangqq"
  # "ihaskell-static-canvas"
  "ihaskell-widgets"
]
