flags: {}
packages:
- '.'
- ipython-kernel/
- ghc-parser/
- ihaskell-display/ihaskell-static-canvas/
- ihaskell-display/ihaskell-charts/
- ihaskell-display/ihaskell-juicypixels/
- ihaskell-display/ihaskell-magic/
- ihaskell-display/ihaskell-rlangqq/
- ihaskell-display/ihaskell-parsec/
- ihaskell-display/ihaskell-plot/
- ihaskell-display/ihaskell-blaze/
- ihaskell-display/ihaskell-widgets/
- ihaskell-display/ihaskell-diagrams/
- ihaskell-display/ihaskell-basic/
- ihaskell-display/ihaskell-aeson/
- ihaskell-display/ihaskell-hatex/
extra-deps:
- active-0.2.0.3
- Chart-1.5
- Chart-cairo-1.5
- diagrams-1.3
- diagrams-cairo-1.3.0.2
- diagrams-contrib-1.3.0.3
- diagrams-core-1.3.0.1
- diagrams-lib-1.3.0.1
- diagrams-solve-0.1
- diagrams-svg-1.3.1.3
- force-layout-0.4.0.1
- happy-1.19.5
- HList-0.4.0.0
- hfsevents-0.1.5
- lucid-svg-0.5.0.0
- magic-1.1
- Rlang-QQ-0.3.1.0
- static-canvas-0.2.0.2
- system-argv0-0.1.1
- vinyl-0.5.1
- xformat-0.1.2.1
resolver: lts-2.18
