resolver: lts-20.13

flags: {}
packages:
    - .
    - ./ipython-kernel
    - ./ghc-parser
    - ./ihaskell-display/ihaskell-aeson
    - ./ihaskell-display/ihaskell-blaze
    - ./ihaskell-display/ihaskell-charts
    - ./ihaskell-display/ihaskell-diagrams
    - ./ihaskell-display/ihaskell-gnuplot
    - ./ihaskell-display/ihaskell-graphviz
    - ./ihaskell-display/ihaskell-hatex
    - ./ihaskell-display/ihaskell-juicypixels
    - ./ihaskell-display/ihaskell-magic
    - ./ihaskell-display/ihaskell-plot
    # - ./ihaskell-display/ihaskell-static-canvas
    - ./ihaskell-display/ihaskell-widgets

ghc-options:
  # Eventually we want "$locals": -Wall -Wpartial-fields -Werror
  # ghc-parser: -Wall -Wpartial-fields -Werror
  # ihaskell: -Wall -Wpartial-fields -Werror
  # ihaskell-widgets: -Wall -Wpartial-fields -Werror

nix:
  enable: false
  packages:
    - blas
    - cairo
    - file
    - gcc
    - gfortran.cc.lib
    - liblapack
    - ncurses
    - pango
    - pkgconfig
    - zeromq
    - zlib
