flags: {}
packages:
    - .
    - ./ipython-kernel
    - ./ghc-parser
    - ./ihaskell-display/ihaskell-aeson
    - ./ihaskell-display/ihaskell-blaze
    - ./ihaskell-display/ihaskell-charts
    - ./ihaskell-display/ihaskell-diagrams
    - ./ihaskell-display/ihaskell-gnuplot
    - ./ihaskell-display/ihaskell-hatex
    - ./ihaskell-display/ihaskell-juicypixels
    - ./ihaskell-display/ihaskell-magic
    - ./ihaskell-display/ihaskell-plot
    - ./ihaskell-display/ihaskell-static-canvas
    - ./ihaskell-display/ihaskell-widgets
resolver: lts-8.8
extra-deps:
    - shelly-1.6.8.3
    - data-accessor-transformers-0.2.1.7
    - gnuplot-0.5.4.1
#    - system-argv0-0.1.1 # Necessary for LTS 2.22 (GHC 7.8)
flags:
  ihaskell:
    binpkgdb: false
