flags: {}
packages:
- '.'
- ipython-kernel/
- ghc-parser/
- ihaskell-display/ihaskell-static-canvas/
- ihaskell-display/ihaskell-charts/
- ihaskell-display/ihaskell-juicypixels/
- ihaskell-display/ihaskell-magic/
- ihaskell-display/ihaskell-rlangqq/
- ihaskell-display/ihaskell-plot/
- ihaskell-display/ihaskell-blaze/
- ihaskell-display/ihaskell-widgets/
- ihaskell-display/ihaskell-diagrams/
- ihaskell-display/ihaskell-basic/
- ihaskell-display/ihaskell-aeson/
- ihaskell-display/ihaskell-hatex/
- ihaskell-display/ihaskell-gnuplot/
extra-deps:
- magic-1.1
- Rlang-QQ-0.3.1.0
- static-canvas-0.2.0.2
- system-argv0-0.1.1
- vinyl-0.5.1
- xformat-0.1.2.1
- ratio-int-0.1.2
- friday-0.2.2.0
- haskell-src-exts-1.17.0
- gnuplot-0.5.4
- data-accessor-transformers-0.2.1.6
resolver: lts-3.14
